services:
  server:
    build:
      context: .
    ports:
      - 21:21
      - 1000-1100:1000-1100
      - 1200-1300:1200-1300
    volumes:
      - ./ftp-data:/ftp-data
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_DB: ftp-server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      timeout: 60s
      retries: 10


